env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux"

live_config_reload: true
strip_formatting: true

window:
  position:
    x: 5
    y: 5
  startup_mode: Maximized
  # Spread additional padding evenly around the terminal content.
  decorations: buttonless
  dynamic_padding: false
  padding:
    x: 18
    y: 16

  # Make background slightly transparent
  opacity: 0.8

font:
  normal:
    family: Hack Nerd Font
  # Font size
  size: 22

hide_cursor_when_typing: true

key_bindings:
  # Vi Mode
  - { key: Space,  mods: Shift|Alt, mode: ~Search,    action: ToggleViMode            }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp   }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown }
  - { key: End,      mods: Shift,   action: ScrollToBottom }
  - { key: Home,     mods: Shift,   action: ScrollToTop    }
  - { key: K,        mods: Command, action: ClearHistory   }
  - { key: K,        mods: Command, chars: "\x0c"          }