[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.cursor]
text = "0x191724"
cursor = "0x796268"

[colors.vi_mode_cursor]
text = "0x191724"
cursor = "0x796268"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.selection]
text = "CellForeground"
background = "0x2A2738"

[colors.normal]
black = "0x6e6a86"
red = "0xeb6f92"
green = "0x9ccfd8"
yellow = "0xf6c177"
blue = "0x31748f"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

[colors.bright]
black = "0x6e6a86"
red = "0xeb6f92"
green = "0x9ccfd8"
yellow = "0xf6c177"
blue = "0x31748f"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"
